version: "3"
services:

  redis:
    image: redis:7-alpine
    restart: always
    # user: '1000'
    volumes:
      - ./data/redis:/data
  
  postgres:
    image: postgres:14-alpine
    restart: always
    # user: '1000'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onlinejudge"]
      interval: 5s
      timeout: 5s
      retries: 3

  judge:
    image: oj-judge
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://judge:8080
      - BACKEND_URL=http://backend:8080/api/judge_server_heartbeat/
      - TOKEN=f939f53b-2fe5-4411-ade2-510bc3e2138a
      # - judger_debug=1

  frontend:
    image: oj-frontend
    restart: always
    # user: '1000'
    volumes:
      - ./data/frontend:/data
    ports:
      - "8080:8080"
      - "8443:8443"

  backend:
    image: oj-backend
    restart: always
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
      judge:
        condition: service_started
    # user: '1000'
    volumes:
      - ./data/backend:/data
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
      - REDIS_HOST=redis
      - JUDGE_SERVER_TOKEN=f939f53b-2fe5-4411-ade2-510bc3e2138a
